name: Build and Deploy to Netlify

on:
  push:
    branches:
      - 'main'      
    paths:
      - 'dress-api-docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./dress-api-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build VitePress Site
        run: npm run docs:build
      - name: Deploy to EdgeOne Pages
        uses: TencentEdgeOne/edgeone-pages-action@v1
        with:
          token: ${{ secrets.EDGEONE_API_TOKEN }}
          project-name: "dress-api-docs"
          build-path: "docs/.vitepress/dist"